### ISSUE TITLE
Move all component-specify style variables from `@taskany/colors/harmony` in each component of `@taskany/bricks/harmony`

### ISSUE THREAD

**Issue by LamaEats** [taskany-inc/bricks#924]
https://github.com/taskany-inc/colors/blob/main/harmony/dark.css#L105-L173

this must be place in `{Component}.module.css` like 

```css
:root {
  --component-specify-var: var(--text-primary);
 /* etc */
}
```
